package be.harm.carshare.cars.car;

import io.swagger.annotations.ApiModelProperty;
import lombok.Builder;
import lombok.Getter;
import lombok.Setter;
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.Transient;

@Builder
public class Car {
    @Transient
    public static final String SEQUENCE_NAME = "users_sequence";

    @Id
    @Setter
    @Getter
    @ApiModelProperty(value = "ID of the car.", example = "1L", notes = "Will be autogenerated when not given.")
    public Long id;

    @ApiModelProperty(value = "ID of the owner of this car.", required = true, example = "1L")
    private Long ownerId;

    @ApiModelProperty(value = "Name of the car", required = true)
    public String name;

    @ApiModelProperty(value = "Brand of the car", required = true, example = "Suzuki")
    public String brand;

    @ApiModelProperty(value = "Model of the car", required = true, example = "Alto")
    public String model;

    @ApiModelProperty(value = "Number of seats in the car", required = true, example = "4")
    public int numberOfSeats;

    @ApiModelProperty(value = "Type of the fuel the car uses", required = true)
    public FuelType fuelType;

    @ApiModelProperty(value = "Whether or not the car is equipped with GPS", required = true)
    public boolean hasGPS;
}
